# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Bifrost Tech Leadership Conf 2019"
email: "comms@fsto.co"
description: "Bifrost conference provides practical training for tech and team leads, managers, cto and any leader in tech!"
baseurl: ""
url: "https://bifrostconf.ca"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-48190009-9"
googleAnalyticsSiteUrl: "bifrostconf.ca"
siteVerification: "JhnAX9iW1D2BK5xvx0jTxlb5NSWR7mlPRRf2PE473BI"

# Organizer Info
organizerName: "Full Stack Toronto"
organizerAlternateName: ""
organizerDescription: "Full Stack Toronto is a non-profit with the goal of advancing people in the web development industry."
organizerEmail: "comms@fsto.co"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://bifrostconf.ca/"

# Head
metaKeywords: "event, leadership, technology, tech lead, team lead, manager, cto, training, workshop, conference"
twitterAccount: "@fullstackto"

# Documents
c4pUrl: "https://www.papercall.io/bifrost-2019"
c4sponsorsUrl: "assets/bifrostsponsorship.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "https://ti.to/fstoco/2019-bifrost-tech-leadership-conference", text: "Buy tickets"}
 - {link: "assets/bifrostsponsorship.pdf", text: "Become a sponsor"}
rightNavigationButtons:
 - {link: "https://ti.to/fstoco/2019-bifrost-tech-leadership-conference", text: "Buy tickets"}
 - {link: "mailto: james.wilkinson@fsto.co", text: "Become a sponsor"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Bifrost Conf, <typeout>"
eventDate: "April 17th, 2019"
typeoutTextValues: '"", "Leadership", "Tools", "Growth"'
typeoutFallback: ""
heroButtons:
  - {link: "https://ti.to/fstoco/2019-bifrost-tech-leadership-conference", text: "Buy tickets"}
  - {link: "assets/bifrostsponsorship.pdf", text: "Become a sponsor"}

# About Block
aboutTitle: "About Bifrost Con"
aboutBlock:
 - {title: "Tools", image: "conference.jpg", text: "We bring you practical and actionable talks on the tools you need to master to succeed, and tools that you can utilise to make your life a little easier as people manager and tech project lead." }
 - {title: "Leadership", image: "workshop.jpg", text: "Advice from your peers on what works and what doesn't work when it comes to leading teams, managing projects, and more in technology." }
 - {title: "Growth", image: "hackathon.jpg", text: "It's not all about growing your team to succeed but also your-self. This track focuses on how to keep yourself gorwing a long with your team." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "", info: "attendees", detail: "from around the world"}
 - {count: "9", specialCharacter: "", info: "speakers", detail: "who've got stories"}
 - {count: "1", specialCharacter: "", info: "day", detail: "of pure engagement"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Featured speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Pantages Hotel Conference Centre"
eventLocationLink: "https://www.pantageshotel.com/"
eventStreetAddress: "200 Victoria St."
eventAddressLocality: "Toronto"
eventAddressLocalityRegion: "Ontario"
eventPostalCode: "M5B 1V8"
eventAddressCountry: "Canada"
eventStartTime: "2019-04-17T08:45"
eventDoorTime: "08:00"
eventEndTime: "2019-04-17T18:00"
eventPlaceCoordinates: "43.6545148, -79.3812063"
mapCenterCoordinates: "43.6545148, -79.3812063"
mapMobileCenterCoordinates: "43.6545148, -79.3812063"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Pantages Hotel"
venueFeatures: ["Steps from Queen Station", "Over 100 nearby restaurants", "Contemporary Style"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to the conference, coffee brakes, and assisted networking. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "149"
  priceCurrency: "CAD"
  ticketsNumber: "50"
  ribbon: "-25%"
  buyButtonLink: "https://ti.to/fstoco/2019-bifrost-tech-leadership-conference"
  buyButtonText: "Buy Now"
  ticketContentList: ["Access to Event", "SWAG Bag", "More to come..."]
  validFrom: "2018-12-01T00:01"
  validThrough: "2019-03-01T23:59"
 -
  name: "General Addmission"
  price: "199"
  priceCurrency: "CAD"
  ticketsNumber: "150"
  buyButtonLink: "https://ti.to/fstoco/2019-bifrost-tech-leadership-conference"
  buyButtonText: "Buy Now"
  ticketContentList: ["Access to Event", "SWAG Bag", "More to come..."]
  validFrom: "2019-03-01T00:01"
  validThrough: "2019-04-13T23:59"
  disabled: true

# Footer
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:comms@fsto.co", text: "Email Us"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Bifrost Conference was started to create a place for team leads, tech leads and other leaders within the tech sector to come together and share practical and actionable knowledge. Bifrost Conference is back again for it’s 3rd year in 2019 and we look forward to welcoming you to Toronto for our unique take on event planing and programming!"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "43.6545148, -79.3812063"
logisticsMapMobileCenterCoordinates: "43.6545148, -79.3812063"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Toronto"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://www.pantageshotel.com/", text: "Pantages"}
     - {link: "https://www.bondplace.ca/", text: "Bond Place"}
     - {link: "https://www.thestrathconahotel.com/", text: "Strathcona Hotel"}
     - {link: "https://www.hotelvictoria-toronto.com/", text: "Hotel Victoria"}
   -
    title: "Restaurants"
    links:
     - {link: "#", text: "Frans"}
     - {link: "#", text: "Subway"}
     - {link: "#", text: "Eaton Centre Food Court"}
     - {link: "#", text: "Popeye's"}
   -
    title: "Networking"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
